### ISSUE TITLE
새로운 기능 건의

### ISSUE THREAD

**Issue by xncbf** [FreeDGroup/TF-BOT#1]
- 단체앨범 만들어주기 (Zoe)
- 점심메뉴 추천 (Zoe)
- polly 를 대체할 Quick vote (Zeo)
- 근무일정 조정 플렉스에 등록, 공지 ex) 오늘 개인 사정으로 9시-6시 근무하겠습니다. (Zeo)
- 그룹원 스케쥴 알림 (Zeo)
- 퇴사자에게 롤링페이퍼 기능 (Zeo)

- 회의실 (보기, 예약)기능 (Francis)
- 사내 유틸 링크 모아보기 (Francis)
- 점심시간 알리미 (Francis)
- 비 (우산필요) 알리미 (Francis)
- azure devops assigned 당할시 1:1로 알려주는 기능 (Francis)
- 생일자 알리미 (Francis)
- 미팅시간에 맞춰서 콜 걸어주기 (Francis)
- 사내멤버 정보 조회하기 (Francis)
- 익명 소원수리함 (Francis)
- 익명 칭찬함 (Francis)

**Comment by ool2o8** [comment]
댓글

**Comment by ool2o8** [comment]
근무일정 조정 플렉스에 등록, 공지 ex) 오늘 개인 사정으로 9시-6시 근무하겠습니다.

**Comment by ool2o8** [comment]
언급 시 휴가인 경우 알림 기능

**Comment by xncbf** [comment]
미팅시간에 맞춰서 콜 걸어주기
사내멤버 정보 조회하기
